import type { Metadata } from 'next'
import { Montserrat, Poppins } from 'next/font/google'
import './globals.css'

export const monserrat = Montserrat({
  variable: '--font-monserrat',
  weight: ['400', '500', '600', '800', '900'],
  subsets: ['latin']
})
export const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['400', '500', '600', '800', '900'],
  subsets: ['latin'],
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="./S.svg" />
        <title>Sige</title>
      </head>
      <body className={`${poppins.variable} ${monserrat.variable}`}>{children}</body>
    </html>
  )
}
